version: '2.4'
services:

  neo4j:
    image: neo4j:3.5
    ports:
      - 7474:7474
      - 7687:7687
    expose:
      - 7474
    container_name: neo4j_docker
    network_mode: "host"
    hostname: localhost
    restart: always
    volumes:
      - /neo4j/data:/data
      - ./neo4j/import:/import
    environment:
      - NEO4J_AUTH=neo4j/1234

  Recommendation-Service:
    build: .
    image: Recommendation-Service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8095:8095
    depends_on:
      - neo4j
